apiVersion: ENC[AES256_GCM,data:H28=,iv:KjXVEme4A+eXEyBGi3nAJhijiEEqJjwh4HcxlffamPk=,tag:loZnbMHoxZ76pHZrOQsltQ==,type:str]
kind: ENC[AES256_GCM,data:wS7eNKyJ,iv:U9CRZWra7EUO7NzGqxKWYgadupt4nCEzSx5vkgfSuBI=,tag:hIkzM85DKxtMacJzPp4wQA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nGVzruN3cB90BRlK73DF7nFg,iv:rjfGhx3N1Ec9ekzMdiis+zguoQj/oIZRSu25KoLbgRw=,tag:2/lKOzqOKiPsjh/R0mOKHA==,type:str]
    namespace: ENC[AES256_GCM,data:1AvvQqEkD8vXfYQmgQ==,iv:2GhcdphmNu7/nuaEEUAQuk2r8nvZ+ijXl+Ik60mdDOE=,tag:aaYTnNYS4ju4MiQl2h+nRg==,type:str]
type: ENC[AES256_GCM,data:/b96Eu7H,iv:HOGxjszrB/f7Sr2Y3NB7bcCLW7+WNJwfkXFysG9fz2U=,tag:8aFnvuWK0cKY1vdTAtGd0Q==,type:str]
stringData:
    tracking_uri: ENC[AES256_GCM,data:nQKwDvevn5Yw7kZTsOYdiboQ,iv:eVKHCUZtC/HTuiVHpmw8ldfpcLB/XmVzkfXWbUgzXDE=,tag:ClAMhx+FD7mhEkNRp0q5Jw==,type:str]
    experiment_name: ENC[AES256_GCM,data:0uwfLl+yGBFwrjnrIQ==,iv:JCtDr8kVUu4Nu+nD/ogOTsfdodjrC6dy2Ja6mmnDv3g=,tag:ALV2JPs/SxRBjzE2Ooa47g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY3RkQk1Xam9KVGU1RmRV
            ZHR5dFFBZU00b2QreXlzSXpQUWRzL2RiRlNzCjJwOVFrdkdFWFZobGp2WDlXbGNr
            UUt2Vy9ZNjcvVktXQk02Y05IZTNrd3MKLS0tIGQzVjNEdG9Wb0R0UnlkUVdvTXU2
            R21KYW5nQmZOODJyMDFFRFpDblZOT2sK8NUg3G/KUhMzBCELuNDxm1sa8X4clwmw
            IeAVncG1r4hgdmJTWlMflsDj8huGbavAhWv5T78K9YljslIKF+6KVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18yqpp46c5ltua9lfpyua03xvac0smaqrmuk2z4n28u6lhn4azu9qgtqqd0
    lastmodified: "2026-06-24T12:40:46Z"
    mac: ENC[AES256_GCM,data:vA/NtM9mU2Sjn8is6GsHNus3wzFQZrA10A93FgeOgVXBQK1wgLHXgyRTBGCaYixMh4+BQ9TiOpP30RMad8Rbsp76g+Xs/EzHcwJ9JrfJYJ2dAJFMNzMsURWQKlyc6Vkarc9FiiiontvKOkxJ4sUBs7uJOo5lDYq0Oa2ck4j5jc8=,iv:xAyPu5FJUGg4SO+fSNbcL4v/y1MTSSDW+jM99gGz4VA=,tag:ve+0mUCCnxjDMi8cXbXfMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
